# Generated by Django 4.0.3 on 2022-11-21 10:06

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authorDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_name', models.CharField(max_length=30, unique=True)),
                ('auth_age', models.IntegerField()),
                ('auth_gender', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'not specified')])),
                ('auth_country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='bookDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=60, unique=True)),
                ('book_date', models.DateField()),
                ('book_pages', models.IntegerField()),
                ('average_critics_rating', models.IntegerField()),
                ('book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authdetails.authordet')),
            ],
        ),
    ]
