# Generated by Django 4.0.3 on 2022-11-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authdetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authordet',
            name='auth_gender',
            field=models.IntegerField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Unspecified')]),
        ),
    ]
