# Generated by Django 4.0.3 on 2022-11-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authdetails', '0003_alter_authordet_auth_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authordet',
            name='auth_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
