# Generated by Django 4.0.3 on 2022-11-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authdetails', '0005_rename_authordet_authordetails_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='authorDetails',
            new_name='authorDet',
        ),
        migrations.RenameModel(
            old_name='bookDetails',
            new_name='bookDet',
        ),
        migrations.RenameField(
            model_name='authordet',
            old_name='author_age',
            new_name='auth_age',
        ),
        migrations.RenameField(
            model_name='authordet',
            old_name='author_country',
            new_name='auth_country',
        ),
        migrations.RenameField(
            model_name='authordet',
            old_name='author_gender',
            new_name='auth_gender',
        ),
        migrations.RenameField(
            model_name='authordet',
            old_name='author_name',
            new_name='auth_name',
        ),
    ]
