# Generated by Django 4.0.3 on 2022-11-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authdetails', '0006_rename_authordetails_authordet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authordet',
            name='auth_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1),
        ),
    ]
