# Generated by Django 4.0.3 on 2022-11-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authdetails', '0007_alter_authordet_auth_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authordet',
            name='auth_name',
            field=models.CharField(max_length=30),
        ),
    ]
